import Head from "next/head";
import Image from "next/image";
import {
  Container,
  Stack,
  VStack,
  HStack,
  Flex,
  Box,
  Spacer,
  Grid,
  GridItem,
  chakra,
  Heading,
  Text,
  Button,
  Progress,
} from "@chakra-ui/react";

const items = [
  {
    id: "01",
    title: "Track company-wide progress.",
    description:
      "See how your day-to-day tasks fit into the wider vision. Go from tracking progress at the milestone level all the way done to the smallest of details. Never lose sight of the bigger picture again.",
  },
  {
    id: "02",
    title: "Advanced built-in reports",
    description:
      "Set internal delivery estimates and track progress toward company goals. Our customisable dashboard helps you build out the reports you need to keep key stakeholders informed.",
  },
  {
    id: "03",
    title: "Everything you need in one place",
    description:
      "Stop jumping from one service to another to communicate, store files, track tasks and share documents. Manage offers an all-in-one team productivity solution.",
  },
];

function Stats() {
  return (
    <chakra.section>
      <Flex justify="center" gap={4} mb={4}>
        <Box w={100} h={100} bg="blue.100">
          box 1
        </Box>
        <Box w={100} h={100} bg="blue.200">
          box 2
        </Box>
      </Flex>
      <Flex justify="center" gap={4} mb={4}>
        <Box w={100} h={100} bg="blue.500">
          box 3
        </Box>
      </Flex>
    </chakra.section>
  );
}

function GetStarted() {
  return (
    <chakra.section>
      <Heading as="h2" size="lg" mb={4}>
        Bring everyone together to build better products.
      </Heading>
      <Text>
        Manage makes it simple for software teams to plan day-to-day tasks while
        keeping the larger team goals in view.
      </Text>
      <Flex justify="center">
        <Button variantColor="blue" mt={4}>
          Get Started
        </Button>
      </Flex>
    </chakra.section>
  );
}

function AboutManage() {
  return (
    <chakra.section>
      <Heading as="h2" size="lg" mb={4}>
        What's different about Manage?
      </Heading>
      <Text>
        Manage provides all the functionality ypur team needs, without the
        complexity. Our software is tailor-made for modern digital product
        teams.
      </Text>

      <AboutManageList items={items} />
    </chakra.section>
  );
}

function AboutManageList({ items }) {
  return (
    <chakra.ul>
      {items.map((item) => {
        return (
          <chakra.li listStyleType="none">
            <Stack>
              <Heading as="h4" size="xs">
                <chakra.span
                  bg="orange.600"
                  color="white"
                  py={2}
                  px={6}
                  borderRadius={40}
                  fontSize="md"
                >
                  {item.id}
                </chakra.span>
                {item.title}
              </Heading>
              <Text>{item.description}</Text>
            </Stack>
          </chakra.li>
        );
      })}
    </chakra.ul>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Manage landing page challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stats />
      <GetStarted />
      <AboutManage />
    </>
  );
}
