import Head from "next/head";
import AboutManage from "../components/about-manage";
import Stats from "../components/stats";
import GetStarted from "../components/get-started";
import SimplifyBox from "../components/simplefy-box";
import Slider from "../components/slider";
import { chakra } from "@chakra-ui/react";

function Section({ children }) {
  return (
    <chakra.section
      width={{ base: "100%", md: "80%" }}
      display="flex"
      flexDirection={{ base: "column-reverse", md: "row" }}
      m={{ base: "0px", md: "0 auto" }}
      my={{ base: "0px", md: "2rem" }}
      justifyContent="space-between"
      alignItems="flex-start"
    >
      {children}
    </chakra.section>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Manage landing page challenge</title>
        <meta
          name="description"
          content="Frontend Mentor Challenge. Generated by create next app"
        />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Section>
        <GetStarted />
        <Stats />
      </Section>

      <Section>
        <AboutManage />
      </Section>

      <Slider />
      <SimplifyBox />
    </>
  );
}
